channels:
  - conda-forge
dependencies:
  - python=3.12
  - compilers
  - numpy
  - fenics-dolfinx=0.8.0
  - mpich
  - petsc=*=complex*
  - scipy
  - matplotlib
  - numba
  - python-gmsh
  - pip
  - libblas
  - libcblas
  - suitesparse
  - swig
  - pip:
    - https://github.com/scikit-umfpack/scikit-umfpack/archive/ce77944bce003a29771ae07be182af348c3eadce.tar.gz