channels:
  - conda-forge
dependencies:
  - python=3.10
  - compilers
  - numpy
  - fenics-dolfinx=0.6.0
  - mpich
  - petsc=*=complex*
  - scipy
  - matplotlib
  - numba
  - pybind11>=2.6.1
  - python-gmsh
  - pip
  - libblas
  - libcblas
  - suitesparse
  - swig
  - pip:
    - scikit-umfpack