channels:
  - conda-forge
dependencies:
  - python=3.12
  - compilers
  - cmake
  - numpy=1.26
  - fenics-dolfinx=0.8
  - mpich
  - petsc=*=complex*
  - scipy=1.13
  - matplotlib
  - numba=0.59
  - python-gmsh=4.12
  - pip
  - libblas
  - libcblas
  - suitesparse=5.10
  - swig
  - pip:
    - https://github.com/scikit-umfpack/scikit-umfpack/archive/ce77944bce003a29771ae07be182af348c3eadce.tar.gz
