channels:
  - conda-forge
dependencies:
  - python=3.12
  - compilers
  - cmake
  - numpy=1.26
  - fenics-dolfinx=0.8
  - openmpi
  - petsc=*=complex*
  - scipy=1.13
  - matplotlib
  - numba=0.59
  - python-gmsh=4.12
